import { redirect } from 'next/navigation';
import { parseCookies } from 'nookies';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { 'mais_cupom.accessToken': accessTOken } = parseCookies();

  if (accessTOken) {
    redirect('/');
  }

  return (
    <div className="grid min-h-full grid-cols-1 lg:grid-cols-2">{children}</div>
  );
}
